true_thetas = [
    1   1   1   0.1 0.5 0.5;
    0.2 1   1   0.1 0.5 0.5;
    1   0.4 0.4 0.1 0.5 0.5;
    0.5 1   1   0.1 1   0.5;
    1   1   1   0.5 0.1 0.5;
];

L = 30;
process_model = process_model2();
amount_of_end_points = 4;

results_directory = fullfile(pwd, "Results");
if ~isfolder(results_directory)
    mkdir(results_directory);
end

for theta_index = 1:size(true_thetas,1)
    true_theta = true_thetas(theta_index,:);
    fprintf("\n===== THETA %d =====\n", theta_index);

    for param_component = 1:6
        switch param_component
            case 1
                param_name = "D";
                parameter_bounds = [0.2,1.8];
            case 2
                param_name = "mu";
                parameter_bounds = [0.2,1.8];
            case 3
                param_name = "K";
                parameter_bounds = [0.2,1.8];
            case 4
                param_name = "r";
                parameter_bounds = [0.00005,1];
            case 5
                param_name = "lambda";
                parameter_bounds = [0.00005,1];
            case 6
                param_name = "m0";
                parameter_bounds = [0.2,0.8];
        end

        for K_i = [21,51]
            for j = 1:2
                T = j*100;
                observation_domain = [0,L;0,T];

                for evaluation_amount_x = [25,50]
                    for base_resolution = [4,8]
                        evaluation_amount_t_per_interval = j * base_resolution;

                        fprintf( ...
                            "Theta=%d | %s | Ki=%d | T=%d | Nx=%d | Nt=%d\n", ...
                            theta_index, ...
                            param_name, ...
                            K_i, ...
                            T, ...
                            evaluation_amount_x, ...
                            evaluation_amount_t_per_interval);

                        rng(100);
                        full_data = observed_data( ...
                            observation_function( ...
                            process_model, ...
                            observation_domain, ...
                            true_theta, ...
                            amount_of_end_points, ...
                            evaluation_amount_x, ...
                            evaluation_amount_t_per_interval), ...
                            true_theta);

                        parfor i = 1:4
                            amount_of_time_points = ...
                                (length(full_data(1,:)) - 1) ...
                                * i / amount_of_end_points + 1;

                            data = full_data(:,1:amount_of_time_points);

                            [npl, ll, conf_int, optimal_parameters, runtime, full_domain] = profile_likelihood( ...
                                param_component, ...
                                observation_domain, ...
                                parameter_bounds, ...
                                data, ...
                                i, ...
                                K_i, ...
                                evaluation_amount_x, ...
                                evaluation_amount_t_per_interval);

                            filename = sprintf( ...
                                'Theta%d_%s_Ki%d_T%d_Nx%d_Nt%d_EP%d.mat', ...
                                theta_index, ...
                                param_name, ...
                                K_i, ...
                                T, ...
                                evaluation_amount_x, ...
                                evaluation_amount_t_per_interval, ...
                                i);

                            filepath = fullfile(results_directory, filename);
                            s = struct( ...
                                'npl', npl, ...
                                'll', ll, ...
                                'conf_int', conf_int, ...
                                'optimal_parameters', optimal_parameters, ...
                                'runtime', runtime, ...
                                'full_domain', full_domain, ...
                                'true_theta', true_theta, ...
                                'theta_index', theta_index, ...
                                'param_component', param_component, ...
                                'param_name', param_name, ...
                                'observation_domain', observation_domain, ...
                                'K_i', K_i, ...
                                'T', T, ...
                                'evaluation_amount_x', evaluation_amount_x, ...
                                'evaluation_amount_t_per_interval', evaluation_amount_t_per_interval, ...
                                'i',i)

                            save(filepath, ...
                                "-fromstruct", ...
                                s);
                        end
                    end
                end
            end
        end
    end
end

disp("ALL PROFILE-LIKELIHOOD CALCULATIONS FINISHED.");
clear